// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOG5LK5teUWsQ_QojoGaMNzLZ5khJ230s',
    appId: '1:727277842842:web:67fb7a3a2cad50ae0d0a23',
    messagingSenderId: '727277842842',
    projectId: 'grocery-app-980ba',
    authDomain: 'grocery-app-980ba.firebaseapp.com',
    storageBucket: 'grocery-app-980ba.appspot.com',
    measurementId: 'G-2B2XQRFBVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxHOufFmjUzt-xo_SsN-vpGOKatVuMUO0',
    appId: '1:727277842842:android:0ba6a0ae499040720d0a23',
    messagingSenderId: '727277842842',
    projectId: 'grocery-app-980ba',
    storageBucket: 'grocery-app-980ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8oc3iTJr4jIE2qlNG3V4BPuO0J2WMxJA',
    appId: '1:727277842842:ios:5afbc2fbbb8954a30d0a23',
    messagingSenderId: '727277842842',
    projectId: 'grocery-app-980ba',
    storageBucket: 'grocery-app-980ba.appspot.com',
    iosBundleId: 'com.example.groceryVendorSide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8oc3iTJr4jIE2qlNG3V4BPuO0J2WMxJA',
    appId: '1:727277842842:ios:773031cde001af960d0a23',
    messagingSenderId: '727277842842',
    projectId: 'grocery-app-980ba',
    storageBucket: 'grocery-app-980ba.appspot.com',
    iosBundleId: 'com.example.groceryVendorSide.RunnerTests',
  );
}
